services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
      - API_BASE_URL=http://localhost:3000
    restart: unless-stopped

  dev:
    image: node:20.9.0-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
      - API_BASE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install -g pnpm@latest && pnpm install && pnpm dev"
    restart: unless-stopped